動画教材ページのジャンル分け
yanbaru-expert/team_project_57 pull request #45
Opened 2021-08-22 09:43 UTC by YasuyukiKuno

#19 

## 実装内容
タスク #16 完了後に行って下さい

- PHP動画教材ページで「PHPの動画教材のみ」が表示されるように修正
  - `PHP動画教材` のリンクをクリックした際のクエリパラメータ `?genre=php` を利用
  - モデルにクラスメソッドを作成して対応できると尚良いでしょう

- 「Ruby/Rails動画教材ページ」のタイトルは「Ruby/Rails動画」、「PHP動画教材ページ」のタイトルは「PHP動画」とする
  - `app/helpers/application_helper.rb` にメソッドを作成して対応できると尚良いでしょう

## 動作確認

- 「Ruby/Rails動画教材」に「PHP動画」が含まれていないことを確認
- 「PHP動画教材」に「PHP動画」のみが表示されていることを確認
- クエリパラメータ `?genre=php` を `php` 以外に変更してアクセスした際は「Ruby/Rails動画教材」が表示されることを確認

2021-08-24 00:28 UTC, great084 requested changes
タイトルが二重で出力されています。
![image](https://user-images.githubusercontent.com/36526480/130536286-4f6611cc-6d0c-468b-bb86-30402ec2ff6a.png)

2021-08-24 00:28 UTC, great084 commented on app/views/movies/index.html.erb
> +<% end %>
`app/helpers/application_helper.rb`でタイトルの出し分けを定義しているので、再度出し分けをする必要はありません。

2021-08-25 14:32 UTC, YasuyukiKuno commented on app/views/movies/index.html.erb
> +<% end %>
ご指摘ありがとうございます。修正しました。

2021-08-26 12:03 UTC, great084 approved these changes
LGTMです！

2021-08-26 12:19 UTC, merged